### ISSUE TITLE
Device Non Responsive for several minutes

### ISSUE THREAD

**Issue by PmSully** [furbrain/SAP5#9]
At about 3 months it starts to refuse to turn on. After a minute of no response, try again and it'll turn on. Gets worse with age. It turns on about 20% of the time now without help. Plugging it in seems to wake it up. That works about 90% of the time, but seems to be losing effectiveness. Any idea for a fix? It's currently updated to the latest patch. Occasionally the display will freeze for 30 seconds during surveys and turn off.

**Comment by imrcly** [comment]
After disconnecting the Bluetooth module the device turns on and off correctly. With the Bluetooth module connected the voltage drops from 3.85v to 3.75v when turned on when the device is not responding to turn on the power stays at 3.75v for 30seconds then the device power returns to 3.85v and the device will turn on again. This does not happen every time. It appears that the Bluetooth module is staying active and not powering off or going into the standby state.
